const amenities = [
  // General Amenities
  { code: 'airConditioning', label: 'Air Conditioning' },
  { code: 'laundryFacilities', label: 'Laundry Facilities' },
  { code: 'fitnessCenter', label: 'Fitness Center' },
  { code: 'elevator', label: 'Elevator' },
  { code: 'wheelchairAccess', label: 'Wheelchair Access' },
  { code: 'doorman', label: 'Doorman' },
  { code: 'parking', label: 'Parking' },
  { code: 'wifi', label: 'WiFi' },
  { code: 'kitchen', label: 'Kitchen' },
  { code: 'dedicatedWorkspace', label: 'Dedicated Workspace' },
  { code: 'hairDryer', label: 'Hair Dryer' },
  { code: 'iron', label: 'Iron' },
  { code: 'heating', label: 'Heating' },
  { code: 'hotTub', label: 'Hot Tub' },
  { code: 'petsAllowed', label: 'Pets Allowed' },
  { code: 'smokingAllowed', label: 'Smoking Allowed' },
  { code: 'eventsAllowed', label: 'Events Allowed' },
  { code: 'privateEntrance', label: 'Private Entrance' },
  { code: 'secure', label: 'Secure' },
  { code: 'waterfront', label: 'Waterfront' },
  { code: 'beachfront', label: 'Beachfront' },
  { code: 'mountainView', label: 'Mountain View' },
  // Washer and Dryer Options
  { code: 'washerInUnit', label: 'Washer In Unit' },
  { code: 'washerHookup', label: 'Washer Hookup' },
  { code: 'washerNotAvailable', label: 'Washer Not Available' },
  { code: 'washerInComplex', label: 'Washer In Complex' },
  { code: 'dryerInUnit', label: 'Dryer In Unit' },
  { code: 'dryerHookup', label: 'Dryer Hookup' },
  { code: 'dryerNotAvailable', label: 'Dryer Not Available' },
  { code: 'dryerInComplex', label: 'Dryer In Complex' },
  // Parking Options
  { code: 'streetParking', label: 'Street Parking' },
  { code: 'streetParkingFree', label: 'Street Parking Free' },
  { code: 'coveredParking', label: 'Covered Parking' },
  { code: 'coveredParkingFree', label: 'Covered Parking Free' },
  { code: 'uncoveredParking', label: 'Uncovered Parking' },
  { code: 'uncoveredParkingFree', label: 'Uncovered Parking Free' },
  { code: 'garageParking', label: 'Garage Parking' },
  { code: 'garageParkingFree', label: 'Garage Parking Free' },
  { code: 'evCharging', label: 'EV Charging' },
  // Pet Policies
  { code: 'allowDogs', label: 'Allow Dogs' },
  { code: 'allowCats', label: 'Allow Cats' },
  // Structural Amenities
  { code: 'gym', label: 'Gym' },
  { code: 'balcony', label: 'Balcony' },
  { code: 'patio', label: 'Patio' },
  { code: 'sunroom', label: 'Sunroom' },
  { code: 'fireplace', label: 'Fireplace' },
  { code: 'firepit', label: 'Firepit' },
  { code: 'pool', label: 'Pool' },
  { code: 'jacuzzi', label: 'Jacuzzi' },
  { code: 'grill', label: 'Grill' },
  { code: 'oven', label: 'Oven' },
  { code: 'stove', label: 'Stove' },
  { code: 'wheelAccessible', label: 'Wheel Accessible' },
  { code: 'fencedInYard', label: 'Fenced In Yard' },
  { code: 'secureLobby', label: 'Secure Lobby' },
  { code: 'keylessEntry', label: 'Keyless Entry' },
  { code: 'alarmSystem', label: 'Alarm System' },
  { code: 'storageShed', label: 'Storage Shed' },
  // Kitchen
  { code: 'garbageDisposal', label: 'Garbage Disposal' },
  { code: 'dishwasher', label: 'Dishwasher' },
  // Furnished
  { code: 'tv', label: 'TV' },
  { code: 'workstation', label: 'Workstation' },
  { code: 'microwave', label: 'Microwave' },
  { code: 'kitchenEssentails', label: 'Kitchen Essentials' },
  { code: 'linens', label: 'Linens' },
  { code: 'privateBathroom', label: 'Private Bathroom' }
];

const iconAmenities = [
  { code: 'wheelchairAccess', label: 'Wheelchair Accessible' },
  { code: 'garbageDisposal', label: 'Garbage Disposal' },
  { code: 'dishwasher', label: 'Dishwasher' },
  { code: 'grill', label: 'Grill' },
  { code: 'uncoveredParkingFree', label: 'Free Parking' },
  { code: 'garageParking', label: 'Garage' },
  { code: 'washerInUnit', label: 'Washer' },
  { code: 'balcony', label: 'Balcony' },
  { code: 'pool', label: 'Pool' },
  { code: 'patio', label: 'Patio' },
  { code: 'porch', label: 'Porch' },
  { code: 'sunroom', label: 'Sunroom' },
  { code: 'gym', label: 'Gym' },
  { code: 'sauna', label: 'Sauna' },
  { code: 'fencedInYard', label: 'Fenced Yard' },
  { code: 'alarmSystem', label: 'Alarm System' },
  { code: 'gatedEntry', label: 'Gated Entry' },
  { code: 'smokeDetector', label: 'Smoke Detector' },
  { code: 'carbonMonoxide', label: 'Carbon Monoxide Detector' },
  { code: 'security', label: 'Security System' },
  { code: 'waterfront', label: 'Waterfront' },
  { code: 'waterview', label: 'Water View' },
  { code: 'mountainView', label: 'Mountain View' },
  { code: 'cityview', label: 'City View' },
]

const highlightAmenities = [
  { code: 'singleFamily', label: 'Single Family Home' },
  { code: 'townhome', label: 'Townhome' },
  { code: 'singleRoom', label: 'Single Room' },
  { code: 'furnished', label: 'Fully Furnished' },
  { code: 'petsAllowed', label: 'Pet Friendly' },
  { code: 'utilitiesIncluded', label: 'Utilities Included' },
]

export { amenities };
