import { Dumbbell } from 'lucide-react';
import * as AmenitiesIcons from '@/components/icons/amenities';

const amenities = [
  // General Amenities
  { code: 'airConditioner', label: 'Air Conditioner', icon: AmenitiesIcons.AirConditioningIcon },
  { code: 'laundryFacilities', label: 'Laundry Facilities', icon: AmenitiesIcons.WasherIcon },
  { code: 'fitnessCenter', label: 'Fitness Center', icon: AmenitiesIcons.GymIcon },
  { code: 'elevator', label: 'Elevator', icon: Dumbbell },
  { code: 'wheelchairAccess', label: 'Wheelchair Access', icon: AmenitiesIcons.WheelchairAccessibleIcon },
  { code: 'doorman', label: 'Doorman', icon: Dumbbell },
  { code: 'parking', label: 'Parking', icon: AmenitiesIcons.ParkingIcon },
  { code: 'wifi', label: 'WiFi', icon: Dumbbell },
  { code: 'kitchen', label: 'Kitchen', icon: Dumbbell },
  { code: 'dedicatedWorkspace', label: 'Dedicated Workspace', icon: AmenitiesIcons.DedicatedWorkspaceIcon },
  { code: 'hairDryer', label: 'Hair Dryer', icon: Dumbbell },
  { code: 'iron', label: 'Iron', icon: Dumbbell },
  { code: 'heater', label: 'Heater', icon: AmenitiesIcons.HeaterIcon },
  { code: 'hotTub', label: 'Hot Tub', icon: AmenitiesIcons.HotTubIcon },
  { code: 'petsAllowed', label: 'Pets Allowed', icon: AmenitiesIcons.PetFriendlyIcon },
  { code: 'smokingAllowed', label: 'Smoking Allowed', icon: Dumbbell },
  { code: 'eventsAllowed', label: 'Events Allowed', icon: Dumbbell },
  { code: 'privateEntrance', label: 'Private Entrance', icon: Dumbbell },
  { code: 'security', label: 'Security', icon: AmenitiesIcons.SecurityIcon },
  { code: 'waterfront', label: 'Waterfront', icon: AmenitiesIcons.WaterfrontIcon },
  { code: 'beachfront', label: 'Beachfront', icon: AmenitiesIcons.WaterfrontIcon },
  { code: 'mountainView', label: 'Mountain View', icon: AmenitiesIcons.MountainViewIcon },
  { code: 'cityView', label: 'City View', icon: AmenitiesIcons.CityViewIcon },
  { code: 'waterView', label: 'Water View', icon: AmenitiesIcons.WaterViewIcon },

  // Washer and Dryer Options
  { code: 'washerInUnit', label: 'Washer In Unit', icon: AmenitiesIcons.WasherIcon },
  { code: 'washerHookup', label: 'Washer Hookup', icon: AmenitiesIcons.WasherIcon },
  { code: 'washerNotAvailable', label: 'Washer Not Available', icon: AmenitiesIcons.WasherIcon },
  { code: 'washerInComplex', label: 'Washer In Complex', icon: AmenitiesIcons.WasherIcon },
  { code: 'dryerInUnit', label: 'Dryer In Unit', icon: AmenitiesIcons.WasherIcon },
  { code: 'dryerHookup', label: 'Dryer Hookup', icon: AmenitiesIcons.WasherIcon },
  { code: 'dryerNotAvailable', label: 'Dryer Not Available', icon: AmenitiesIcons.WasherIcon },
  { code: 'dryerInComplex', label: 'Dryer In Complex', icon: AmenitiesIcons.WasherIcon },
  // Parking Options
  { code: 'streetParking', label: 'Street Parking', icon: AmenitiesIcons.ParkingIcon },
  { code: 'streetParkingFree', label: 'Street Parking Free', icon: AmenitiesIcons.ParkingIcon },
  { code: 'coveredParking', label: 'Covered Parking', icon: AmenitiesIcons.ParkingIcon },
  { code: 'coveredParkingFree', label: 'Covered Parking Free', icon: AmenitiesIcons.ParkingIcon },
  { code: 'uncoveredParking', label: 'Uncovered Parking', icon: AmenitiesIcons.ParkingIcon },
  { code: 'uncoveredParkingFree', label: 'Uncovered Parking Free', icon: AmenitiesIcons.ParkingIcon },
  { code: 'garageParking', label: 'Garage Parking', icon: AmenitiesIcons.ParkingIcon },
  { code: 'garageParkingFree', label: 'Garage Parking Free', icon: AmenitiesIcons.ParkingIcon },
  { code: 'evCharging', label: 'EV Charging', icon: AmenitiesIcons.EvChargingIcon },

  // Pet Policies
  { code: 'allowDogs', label: 'Allow Dogs', icon: Dumbbell },
  { code: 'allowCats', label: 'Allow Cats', icon: Dumbbell },
  // Structural Amenities
  { code: 'gym', label: 'Gym', icon: AmenitiesIcons.GymIcon },
  { code: 'balcony', label: 'Balcony', icon: AmenitiesIcons.BalconyIcon },
  { code: 'patio', label: 'Patio', icon: AmenitiesIcons.PatioIcon },
  { code: 'sunroom', label: 'Sunroom', icon: AmenitiesIcons.SunroomIcon },
  { code: 'fireplace', label: 'Fireplace', icon: AmenitiesIcons.FireplaceIcon },
  { code: 'firepit', label: 'Firepit', icon: Dumbbell },
  { code: 'pool', label: 'Pool', icon: AmenitiesIcons.PoolIcon },
  { code: 'sauna', label: 'Sauna', icon: AmenitiesIcons.SaunaIcon },
  { code: 'jacuzzi', label: 'Jacuzzi', icon: AmenitiesIcons.HotTubIcon },
  { code: 'grill', label: 'Grill', icon: AmenitiesIcons.GrillIcon },
  { code: 'oven', label: 'Oven', icon: AmenitiesIcons.OvenIcon },
  { code: 'stove', label: 'Stove', icon: Dumbbell },
  { code: 'wheelAccessible', label: 'Wheel Accessible', icon: AmenitiesIcons.WheelchairAccessibleIcon },
  { code: 'fencedInYard', label: 'Fenced In Yard', icon: AmenitiesIcons.FencedYardIcon },
  { code: 'secureLobby', label: 'Secure Lobby', icon: AmenitiesIcons.SecurityIcon },
  { code: 'keylessEntry', label: 'Keyless Entry', icon: AmenitiesIcons.KeylessEntryIcon },
  { code: 'alarmSystem', label: 'Alarm System', icon: AmenitiesIcons.AlarmSystemIcon },
  { code: 'storageShed', label: 'Storage Shed', icon: Dumbbell },
  { code: 'gatedEntry', label: 'Gated Entry', icon: AmenitiesIcons.GatedEntryIcon },
  { code: 'smokeDetector', label: 'Smoke Detector', icon: AmenitiesIcons.SmokeDetectorIcon },
  { code: 'carbonMonoxide', label: 'Carbon Monoxide Detector', icon: AmenitiesIcons.CarbonMonoxideDetectorIcon },

  // Kitchen
  { code: 'garbageDisposal', label: 'Garbage Disposal', icon: AmenitiesIcons.GarbageDisposalIcon },
  { code: 'dishwasher', label: 'Dishwasher', icon: AmenitiesIcons.DishwasherIcon },
  { code: 'fridge', label: 'Refrigerator', icon: AmenitiesIcons.FridgeIcon },
  // Furnished
  { code: 'tv', label: 'TV', icon: Dumbbell },
  { code: 'workstation', label: 'Workstation', icon: Dumbbell },
  { code: 'microwave', label: 'Microwave', icon: Dumbbell },
  { code: 'kitchenEssentials', label: 'Kitchen Essentials', icon: AmenitiesIcons.KitchenEssentialsIcon },
  { code: 'linens', label: 'Linens', icon: Dumbbell },
  { code: 'privateBathroom', label: 'Private Bathroom', icon: Dumbbell },
  { code: 'kitchenEssentials', label: 'Kitchen Essentials' },
  { code: 'linens', label: 'Linens' },
]

export const iconAmenities = [
  { code: 'wheelchairAccess', label: 'Wheelchair Accessible', icon: AmenitiesIcons.WheelchairAccessibleIcon },
  { code: 'garbageDisposal', label: 'Garbage Disposal', icon: AmenitiesIcons.GarbageDisposalIcon },
  { code: 'dishwasher', label: 'Dishwasher', icon: AmenitiesIcons.DishwasherIcon },
  { code: 'grill', label: 'Grill', icon: AmenitiesIcons.GrillIcon },
  { code: 'uncoveredParkingFree', label: 'Free Parking', icon: AmenitiesIcons.ParkingIcon },
  { code: 'garageParking', label: 'Garage', icon: AmenitiesIcons.ParkingIcon },
  { code: 'washerInUnit', label: 'In Unit', icon: AmenitiesIcons.WasherIcon },
  { code: 'washerInComplex', label: 'In Complex', icon: AmenitiesIcons.WasherIcon },
  { code: 'balcony', label: 'Balcony', icon: AmenitiesIcons.BalconyIcon },
  { code: 'pool', label: 'Pool', icon: AmenitiesIcons.PoolIcon },
  { code: 'patio', label: 'Patio', icon: AmenitiesIcons.PatioIcon },
  { code: 'sunroom', label: 'Sunroom', icon: AmenitiesIcons.SunroomIcon },
  { code: 'gym', label: 'Gym', icon: AmenitiesIcons.GymIcon },
  { code: 'sauna', label: 'Sauna', icon: AmenitiesIcons.SaunaIcon },
  { code: 'hotTub', label: 'Hot Tub', icon: AmenitiesIcons.HotTubIcon },
  { code: 'fencedInYard', label: 'Fenced Yard', icon: AmenitiesIcons.FencedYardIcon },
  { code: 'alarmSystem', label: 'Alarm System', icon: AmenitiesIcons.AlarmSystemIcon },
  { code: 'gatedEntry', label: 'Gated Entry', icon: AmenitiesIcons.GatedEntryIcon },
  { code: 'smokeDetector', label: 'Smoke Detector', icon: AmenitiesIcons.SmokeDetectorIcon },
  { code: 'carbonMonoxide', label: 'CO Detector', icon: AmenitiesIcons.CarbonMonoxideDetectorIcon },
  { code: 'security', label: 'Security System', icon: AmenitiesIcons.SecurityIcon },
  { code: 'waterfront', label: 'Waterfront', icon: AmenitiesIcons.WaterfrontIcon },
  { code: 'waterView', label: 'Water View', icon: AmenitiesIcons.WaterViewIcon },
  { code: 'mountainView', label: 'Mountain View', icon: AmenitiesIcons.MountainViewIcon },
  { code: 'cityView', label: 'City View', icon: AmenitiesIcons.CityViewIcon },
]

export const highlightAmenities = [
  { code: 'singleFamily', label: 'Single Family Home', icon: AmenitiesIcons.SingleFamilyIcon },
  { code: 'townhome', label: 'Townhome', icon: AmenitiesIcons.TownhouseIcon },
  { code: 'singleRoom', label: 'Single Room', icon: AmenitiesIcons.SingleRoomIcon },
  { code: 'furnished', label: 'Fully Furnished', icon: AmenitiesIcons.FurnishedIcon, falseIcon: AmenitiesIcons.UnfurnishedIcon },
  { code: 'petsAllowed', label: 'Pet Friendly', icon: AmenitiesIcons.PetFriendlyIcon, falseIcon: AmenitiesIcons.PetUnfriendlyIcon },
  { code: 'utilitiesIncluded', label: 'Utilities Included', icon: AmenitiesIcons.UtilitiesIncludedIcon, falseIcon: AmenitiesIcons.UtilitiesNotIncludedIcon },
]

export { amenities };
