import type {
  RenterDashboardData,
  DashboardTrip,
  DashboardBooking,
  DashboardMatch,
  DashboardApplication,
  DashboardFavorite,
  DashboardListing,
} from '@/app/actions/renter-dashboard';

function makeListing(
  id: string,
  title: string,
  city: string,
  state: string,
  imageIndex: number,
  price: number,
  opts?: { rooms?: number; baths?: number; category?: string }
): DashboardListing {
  return {
    id,
    title,
    category: opts?.category || 'Apartment',
    roomCount: opts?.rooms ?? 2,
    bathroomCount: opts?.baths ?? 1,
    streetAddress1: '123 Main St',
    city,
    state,
    postalCode: '46201',
    shortestLeasePrice: price,
    listingImages: [
      { id: `img-${id}-1`, url: `/placeholderImages/image_${imageIndex}.jpg` },
      { id: `img-${id}-2`, url: `/placeholderImages/image_${((imageIndex % 30) + 1)}.jpg` },
    ],
    monthlyPricing: [{ price }],
  };
}

const demoRecentSearches: DashboardTrip[] = [
  {
    id: 'demo-trip-1',
    locationString: 'Indianapolis, Indiana',
    city: 'Indianapolis',
    state: 'Indiana',
    startDate: new Date('2025-03-01'),
    endDate: new Date('2025-06-01'),
    numAdults: 2,
    numChildren: 0,
    numPets: 1,
    createdAt: new Date('2025-02-10'),
  },
  {
    id: 'demo-trip-2',
    locationString: 'Chicago, Illinois',
    city: 'Chicago',
    state: 'Illinois',
    startDate: new Date('2025-04-15'),
    endDate: new Date('2025-07-15'),
    numAdults: 1,
    numChildren: 0,
    numPets: 0,
    createdAt: new Date('2025-02-08'),
  },
  {
    id: 'demo-trip-3',
    locationString: 'Nashville, Tennessee',
    city: 'Nashville',
    state: 'Tennessee',
    startDate: new Date('2025-05-01'),
    endDate: new Date('2025-08-31'),
    numAdults: 3,
    numChildren: 1,
    numPets: 0,
    createdAt: new Date('2025-02-05'),
  },
  {
    id: 'demo-trip-4',
    locationString: 'Austin, Texas',
    city: 'Austin',
    state: 'Texas',
    startDate: new Date('2025-06-01'),
    endDate: new Date('2025-09-01'),
    numAdults: 2,
    numChildren: 2,
    numPets: 1,
    createdAt: new Date('2025-01-28'),
  },
  {
    id: 'demo-trip-5',
    locationString: 'Denver, Colorado',
    city: 'Denver',
    state: 'Colorado',
    startDate: new Date('2025-03-15'),
    endDate: new Date('2025-05-15'),
    numAdults: 1,
    numChildren: 0,
    numPets: 2,
    createdAt: new Date('2025-01-20'),
  },
  {
    id: 'demo-trip-6',
    locationString: 'Columbus, Ohio',
    city: 'Columbus',
    state: 'Ohio',
    startDate: new Date('2025-07-01'),
    endDate: new Date('2025-12-31'),
    numAdults: 2,
    numChildren: 0,
    numPets: 0,
    createdAt: new Date('2025-01-15'),
  },
];

const demoBookings: DashboardBooking[] = [
  {
    id: 'demo-booking-1',
    listingId: 'demo-listing-b1',
    tripId: 'demo-trip-1',
    startDate: new Date('2025-03-01'),
    endDate: new Date('2025-06-01'),
    monthlyRent: 1450,
    status: 'confirmed',
    listing: {
      title: 'Sunny Broad Ripple Apartment',
      imageSrc: null,
      userId: 'demo-host-1',
      locationString: 'Indianapolis, Indiana',
      listingImages: [
        { id: 'img-b1-1', url: '/placeholderImages/image_1.jpg' },
        { id: 'img-b1-2', url: '/placeholderImages/image_2.jpg' },
      ],
    },
    trip: { numAdults: 2, numPets: 1, numChildren: 0 },
  },
  {
    id: 'demo-booking-2',
    listingId: 'demo-listing-b2',
    tripId: 'demo-trip-2',
    startDate: new Date('2025-04-15'),
    endDate: new Date('2025-07-15'),
    monthlyRent: 2100,
    status: 'confirmed',
    listing: {
      title: 'Modern Loop Studio',
      imageSrc: null,
      userId: 'demo-host-2',
      locationString: 'Chicago, Illinois',
      listingImages: [
        { id: 'img-b2-1', url: '/placeholderImages/image_3.jpg' },
        { id: 'img-b2-2', url: '/placeholderImages/image_4.jpg' },
      ],
    },
    trip: { numAdults: 1, numPets: 0, numChildren: 0 },
  },
  {
    id: 'demo-booking-3',
    listingId: 'demo-listing-b3',
    tripId: 'demo-trip-3',
    startDate: new Date('2025-05-01'),
    endDate: new Date('2025-08-31'),
    monthlyRent: 1800,
    status: 'pending',
    listing: {
      title: 'Cozy East Nashville Bungalow',
      imageSrc: null,
      userId: 'demo-host-3',
      locationString: 'Nashville, Tennessee',
      listingImages: [
        { id: 'img-b3-1', url: '/placeholderImages/image_5.jpg' },
        { id: 'img-b3-2', url: '/placeholderImages/image_6.jpg' },
      ],
    },
    trip: { numAdults: 3, numPets: 0, numChildren: 1 },
  },
];

const demoMatches: DashboardMatch[] = [
  {
    id: 'demo-match-1',
    tripId: 'demo-trip-1',
    listingId: 'demo-listing-m1',
    monthlyRent: 1350,
    listing: makeListing('demo-listing-m1', 'Downtown Loft with City Views', 'Indianapolis', 'Indiana', 7, 1350, { rooms: 1, baths: 1, category: 'Apartment' }),
  },
  {
    id: 'demo-match-2',
    tripId: 'demo-trip-1',
    listingId: 'demo-listing-m2',
    monthlyRent: 1600,
    listing: makeListing('demo-listing-m2', 'Fountain Square Townhome', 'Indianapolis', 'Indiana', 9, 1600, { rooms: 3, baths: 2, category: 'Townhouse' }),
  },
  {
    id: 'demo-match-3',
    tripId: 'demo-trip-2',
    listingId: 'demo-listing-m3',
    monthlyRent: 2200,
    listing: makeListing('demo-listing-m3', 'Wicker Park 2BR', 'Chicago', 'Illinois', 11, 2200, { rooms: 2, baths: 1 }),
  },
  {
    id: 'demo-match-4',
    tripId: 'demo-trip-2',
    listingId: 'demo-listing-m4',
    monthlyRent: 1950,
    listing: makeListing('demo-listing-m4', 'Lincoln Park Garden Unit', 'Chicago', 'Illinois', 13, 1950, { rooms: 2, baths: 1 }),
  },
  {
    id: 'demo-match-5',
    tripId: 'demo-trip-3',
    listingId: 'demo-listing-m5',
    monthlyRent: 1700,
    listing: makeListing('demo-listing-m5', 'The Gulch Modern Flat', 'Nashville', 'Tennessee', 15, 1700, { rooms: 1, baths: 1 }),
  },
  {
    id: 'demo-match-6',
    tripId: 'demo-trip-4',
    listingId: 'demo-listing-m6',
    monthlyRent: 1550,
    listing: makeListing('demo-listing-m6', 'South Congress Cottage', 'Austin', 'Texas', 17, 1550, { rooms: 2, baths: 1, category: 'House' }),
  },
  {
    id: 'demo-match-7',
    tripId: 'demo-trip-5',
    listingId: 'demo-listing-m7',
    monthlyRent: 1800,
    listing: makeListing('demo-listing-m7', 'RiNo District Loft', 'Denver', 'Colorado', 19, 1800, { rooms: 1, baths: 1, category: 'Apartment' }),
  },
  {
    id: 'demo-match-8',
    tripId: 'demo-trip-6',
    listingId: 'demo-listing-m8',
    monthlyRent: 1400,
    listing: makeListing('demo-listing-m8', 'Short North Condo', 'Columbus', 'Ohio', 21, 1400, { rooms: 2, baths: 2 }),
  },
];

const demoApplications: DashboardApplication[] = [
  {
    id: 'demo-app-1',
    tripId: 'demo-trip-1',
    listingId: 'demo-listing-a1',
    status: 'pending',
    startDate: new Date('2025-03-01'),
    endDate: new Date('2025-06-01'),
    createdAt: new Date('2025-02-09'),
    hasMatch: false,
    listing: {
      ...makeListing('demo-listing-a1', 'Mass Ave Artist Studio', 'Indianapolis', 'Indiana', 23, 1200, { rooms: 1, baths: 1 }),
      user: { id: 'demo-host-4', firstName: 'Sarah', lastName: 'Johnson' },
    },
    trip: { numAdults: 2, numPets: 1, numChildren: 0 },
  },
  {
    id: 'demo-app-2',
    tripId: 'demo-trip-2',
    listingId: 'demo-listing-a2',
    status: 'pending',
    startDate: new Date('2025-04-15'),
    endDate: new Date('2025-07-15'),
    createdAt: new Date('2025-02-07'),
    hasMatch: false,
    listing: {
      ...makeListing('demo-listing-a2', 'Lakeview High-Rise', 'Chicago', 'Illinois', 25, 2400, { rooms: 2, baths: 2 }),
      user: { id: 'demo-host-5', firstName: 'Mike', lastName: 'Chen' },
    },
    trip: { numAdults: 1, numPets: 0, numChildren: 0 },
  },
  {
    id: 'demo-app-3',
    tripId: 'demo-trip-3',
    listingId: 'demo-listing-a3',
    status: 'pending',
    startDate: new Date('2025-05-01'),
    endDate: new Date('2025-08-31'),
    createdAt: new Date('2025-02-04'),
    hasMatch: false,
    listing: {
      ...makeListing('demo-listing-a3', 'Germantown Victorian', 'Nashville', 'Tennessee', 27, 1900, { rooms: 3, baths: 2, category: 'House' }),
      user: { id: 'demo-host-6', firstName: 'Emily', lastName: 'Davis' },
    },
    trip: { numAdults: 3, numPets: 0, numChildren: 1 },
  },
];

const demoFavorites: DashboardFavorite[] = [
  {
    id: 'demo-fav-1',
    tripId: 'demo-trip-1',
    listingId: 'demo-listing-f1',
    isApplied: true,
    createdAt: new Date('2025-02-10'),
    listing: makeListing('demo-listing-f1', 'Irvington Craftsman Home', 'Indianapolis', 'Indiana', 2, 1500, { rooms: 3, baths: 2, category: 'House' }),
  },
  {
    id: 'demo-fav-2',
    tripId: 'demo-trip-1',
    listingId: 'demo-listing-f2',
    isApplied: false,
    createdAt: new Date('2025-02-09'),
    listing: makeListing('demo-listing-f2', 'Meridian-Kessler Duplex', 'Indianapolis', 'Indiana', 4, 1650, { rooms: 2, baths: 1 }),
  },
  {
    id: 'demo-fav-3',
    tripId: 'demo-trip-2',
    listingId: 'demo-listing-f3',
    isApplied: false,
    createdAt: new Date('2025-02-08'),
    listing: makeListing('demo-listing-f3', 'Bucktown Brownstone', 'Chicago', 'Illinois', 6, 2300, { rooms: 2, baths: 2 }),
  },
  {
    id: 'demo-fav-4',
    tripId: 'demo-trip-3',
    listingId: 'demo-listing-f4',
    isApplied: false,
    createdAt: new Date('2025-02-07'),
    listing: makeListing('demo-listing-f4', '12 South Retreat', 'Nashville', 'Tennessee', 8, 1750, { rooms: 2, baths: 1, category: 'House' }),
  },
  {
    id: 'demo-fav-5',
    tripId: 'demo-trip-4',
    listingId: 'demo-listing-f5',
    isApplied: true,
    createdAt: new Date('2025-02-06'),
    listing: makeListing('demo-listing-f5', 'East Austin Bungalow', 'Austin', 'Texas', 10, 1600, { rooms: 2, baths: 1, category: 'House' }),
  },
  {
    id: 'demo-fav-6',
    tripId: 'demo-trip-5',
    listingId: 'demo-listing-f6',
    isApplied: false,
    createdAt: new Date('2025-02-05'),
    listing: makeListing('demo-listing-f6', 'Capitol Hill Condo', 'Denver', 'Colorado', 12, 1850, { rooms: 1, baths: 1 }),
  },
  {
    id: 'demo-fav-7',
    tripId: 'demo-trip-6',
    listingId: 'demo-listing-f7',
    isApplied: false,
    createdAt: new Date('2025-02-04'),
    listing: makeListing('demo-listing-f7', 'German Village Flat', 'Columbus', 'Ohio', 14, 1300, { rooms: 2, baths: 1 }),
  },
  {
    id: 'demo-fav-8',
    tripId: 'demo-trip-1',
    listingId: 'demo-listing-f8',
    isApplied: false,
    createdAt: new Date('2025-02-03'),
    listing: makeListing('demo-listing-f8', 'SoBro Modern Apartment', 'Indianapolis', 'Indiana', 16, 1400, { rooms: 1, baths: 1 }),
  },
];

export function getDemoData(userId: string, firstName: string | null, lastName: string | null, imageUrl: string): RenterDashboardData {
  return {
    user: {
      id: userId,
      firstName,
      lastName,
      imageUrl,
    },
    recentSearches: demoRecentSearches,
    bookings: demoBookings,
    matches: demoMatches,
    applications: demoApplications,
    favorites: demoFavorites,
    hasMoreFavorites: false,
  };
}
