import React from "react";

export const BackgroundCheckAuthorizationContent = (): JSX.Element => {
  return (
    <div className="space-y-4 text-sm text-[#5d606d] font-['Poppins',Helvetica]">
      <h2 className="text-center text-lg font-semibold text-[#373940]">
        Rental Background Report Authorization and Disclosure Form
      </h2>

      <p className="font-semibold text-[#373940]">
        PLEASE READ THIS RENTAL BACKGROUND REPORT AUTHORIZATION AND DISCLOSURE FORM
        (&ldquo;AUTHORIZATION FORM&rdquo;) CAREFULLY BEFORE CHECKING THE BOX BELOW TO INDICATE
        YOUR AUTHORIZATION.
      </p>

      <p>
        This Rental Background Report Authorization and Disclosure Form (&ldquo;<strong>Authorization
        Form</strong>&rdquo;) supplements the MatchBook Terms and Conditions (&ldquo;<strong>Agreement</strong>&rdquo;)
        between MatchBook, LLC (&ldquo;<strong>MatchBook</strong>&rdquo;) and you, the renter applicant
        (&ldquo;<strong>you</strong>&rdquo;).
      </p>

      <p>
        By checking the electronic signature consent box below, you authorize MatchBook, in connection
        with your rental application on the MatchBook platform, to obtain a background report about
        you from a background screening agency, in compliance with the federal Fair Credit Reporting
        Act (&ldquo;FCRA&rdquo;), 15 U.S.C. &sect; 1681 et seq., and applicable state laws.
      </p>

      <p>You understand and agree that:</p>

      <ol className="list-decimal list-outside ml-6 space-y-3">
        <li>
          <strong>Purpose of Authorization Form</strong>. This Authorization Form governs the
          collection, use, and disclosure of background screening information, including information
          derived from criminal, civil, and eviction records, by MatchBook for the purpose of
          evaluating your rental application and, with your express consent, sharing such information
          with potential landlords or property managers (each, a &ldquo;<strong>Host</strong>&rdquo;).
        </li>

        <li>
          <strong>Information Collected</strong>. You understand that your background report may
          include, but is not limited to, information regarding personal identifier information;
          criminal convictions; pending criminal cases (to the extent permitted by law) and eviction
          records; and other public records relevant to renter screening. Arrest records not resulting
          in conviction, sealed or expunged records, and other records prohibited by law will not be
          considered.
        </li>

        <li>
          <strong>Creation of Derived Background Information</strong>. You authorize MatchBook to
          analyze your background report to create Derived Background Information. For purposes of
          this Authorization Form, &ldquo;<strong>Derived Background Information</strong>&rdquo; means
          information generated by MatchBook from your background report for renter screening purposes.
          This may include a limited summary derived from third-party background information, which may
          include a summary of criminal history, eviction history, or other similar information, but
          does not include disclosure of your full background report or underlying source data.
        </li>

        <li>
          <strong>Redistribution of Derived Background Information</strong>. You authorize MatchBook,
          upon your express consent for each disclosure, to share Derived Background Information with
          potential Hosts for the limited purpose of evaluating your suitability as a renter. Each
          disclosure request will identify (a) the name and contact information of the Host, (b) the
          property address for which the information is requested, (c) a description of the Derived
          Background Information to be shared, and (d) the date and time of the request. MatchBook
          will not disclose or redistribute Derived Background Information to any other person or
          entity without your separate, express consent for each such disclosure.
        </li>

        <li>
          <strong>Renter Rights</strong>. You retain the right to:
          <ul className="list-disc list-outside ml-6 mt-2 space-y-1">
            <li>decline any request for redistribution of Derived Background Information;</li>
            <li>
              revoke your consent under this Authorization Form at any time by providing written
              notice to MatchBook;
            </li>
            <li>
              request a list of all Hosts who have received your Derived Background Information; and
            </li>
            <li>
              dispute the accuracy of any Derived Background Information by contacting MatchBook
              directly.
            </li>
          </ul>
        </li>

        <li>
          <strong>MatchBook Obligations</strong>. MatchBook agrees to:
          <ul className="list-disc list-outside ml-6 mt-2 space-y-1">
            <li>
              maintain appropriate administrative, technical, and physical safeguards to protect
              your information;
            </li>
            <li>
              use Derived Background Information solely for the purpose of facilitating rental
              applications;
            </li>
            <li>comply with the redistribution requirements set forth in Section 4; and</li>
            <li>
              comply with all applicable provisions of the FCRA and state consumer-privacy and
              background-screening laws.
            </li>
          </ul>
        </li>

        <li>
          <strong>No Other Use</strong>. Your background report and any Derived Background Information
          will be used solely for rental application and renter screening purposes and will not be
          sold or shared for marketing, advertising, or any unrelated purpose.
        </li>

        <li>
          <strong>Retention</strong>. MatchBook and participating Hosts may retain Derived Background
          Information and screening results for as long as reasonably necessary to fulfill rental
          application and record-keeping requirements, subject to applicable law.
        </li>

        <li>
          <strong>FCRA Rights</strong>. You understand that you have the right under the FCRA to
          request a copy of any background report obtained about you and to dispute any inaccurate
          or incomplete information. If any adverse action is taken against you based in whole or
          in part on information from a background report, you will receive an Adverse Action Notice
          explaining the action taken and your rights under the FCRA.
        </li>

        <li>
          <strong>Consent to Receive Electronic Notices</strong>. You expressly consent to receive
          notices electronically by email.
        </li>
      </ol>
    </div>
  );
};
