import React from "react";

export const CreditCheckAuthorizationContent = (): JSX.Element => {
  return (
    <div className="space-y-4 text-sm text-[#5d606d] font-['Poppins',Helvetica]">
      <h2 className="text-center text-lg font-semibold text-[#373940]">
        Rental Credit Report Authorization and Disclosure Form
      </h2>

      <p className="font-semibold text-[#373940]">
        PLEASE READ THIS RENTAL CREDIT REPORT AUTHORIZATION AND DISCLOSURE
        (&ldquo;AUTHORIZATION FORM&rdquo;) CAREFULLY BEFORE CHECKING THE BOX BELOW TO INDICATE
        YOUR AUTHORIZATION.
      </p>

      <p>
        This Rental Credit Report Authorization and Disclosure Form (&ldquo;<strong>Authorization
        Form</strong>&rdquo;) supplements the MatchBook Terms and Conditions (&ldquo;<strong>Agreement</strong>&rdquo;)
        between MatchBook, LLC (&ldquo;<strong>MatchBook</strong>&rdquo;) and you, the renter applicant
        (&ldquo;<strong>you</strong>&rdquo;).
      </p>

      <p>
        By checking the electronic signature consent box below, you authorize MatchBook, in connection
        with your rental application on the MatchBook platform, to obtain a consumer credit report
        about you from a consumer reporting agency, in compliance with the federal Fair Credit
        Reporting Act (&ldquo;FCRA&rdquo;), 15 U.S.C. &sect; 1681 et seq., and applicable state laws.
      </p>

      <p>You understand and agree that:</p>

      <ol className="list-decimal list-outside ml-6 space-y-3">
        <li>
          <strong>Purpose of Authorization Form</strong>. This Authorization Form governs the
          collection, use, and disclosure of tenant screening information, including information
          derived from your consumer credit report (&ldquo;<strong>Consumer Report</strong>&rdquo;),
          by MatchBook for the purpose of evaluating your rental application and, with your express
          consent, sharing such information with potential landlords or property managers (each, a
          &ldquo;<strong>Host</strong>&rdquo;).
        </li>

        <li>
          <strong>Information Collected</strong>. You understand that your Consumer Report may
          include, but is not limited to, information regarding credit history; outstanding debts,
          collections, or charge-offs; loan and credit card applications and inquiries; public
          records relating to financial judgments; and information reported by lenders, creditors,
          or financial institutions.
        </li>

        <li>
          <strong>Creation of Derived Tenant Information</strong>. You authorize MatchBook to
          analyze your Consumer Report to create Derived Tenant Information. For purposes of this
          Authorization Form, &ldquo;<strong>Derived Tenant Information</strong>&rdquo; means
          information generated by MatchBook from your Consumer Report for tenant-screening purposes.
          This may include risk assessments, eligibility indicators, or screening categories produced
          through proprietary models, but does not include disclosure of your full Consumer Report
          or raw credit score.
        </li>

        <li>
          <strong>Redistribution of Derived Tenant Information</strong>. You authorize MatchBook,
          upon your express consent for each disclosure, to share Derived Tenant Information with
          potential Hosts for the limited purpose of evaluating your suitability as a tenant. Each
          disclosure request will identify: (a) the name and contact information of the Host;
          (b) the property address for which the information is requested; (c) a description of
          the Derived Tenant Information to be shared; and (d) the date and time of the request.
          MatchBook will not disclose or redistribute Derived Tenant Information to any other
          person or entity without your separate, express consent for each such disclosure.
        </li>

        <li>
          <strong>Tenant Rights</strong>. You retain the right to:
          <ul className="list-disc list-outside ml-6 mt-2 space-y-1">
            <li>decline any request for redistribution of Derived Tenant Information;</li>
            <li>
              revoke your consent under this Authorization Form at any time by providing written
              notice to MatchBook;
            </li>
            <li>
              request a list of all Hosts who have received your Derived Tenant Information; and
            </li>
            <li>
              dispute the accuracy of any Derived Tenant Information by contacting MatchBook
              directly.
            </li>
          </ul>
        </li>

        <li>
          <strong>MatchBook Obligations</strong>. MatchBook agrees to:
          <ul className="list-disc list-outside ml-6 mt-2 space-y-1">
            <li>
              maintain appropriate administrative, technical, and physical safeguards to protect
              your information;
            </li>
            <li>
              use Derived Tenant Information solely for the purpose of facilitating rental
              applications;
            </li>
            <li>comply with the redistribution requirements set forth in Section 4; and</li>
            <li>
              comply with all applicable provisions of the FCRA and state consumer privacy laws.
            </li>
          </ul>
        </li>

        <li>
          <strong>No Other Use</strong>. Your Consumer Report and any Derived Tenant Information
          will be used solely for rental application and renter screening purposes and will not
          be sold or shared for marketing, advertising, or any unrelated purpose.
        </li>

        <li>
          <strong>Retention</strong>. MatchBook and participating Hosts may retain Derived Tenant
          Information and screening results for as long as reasonably necessary to fulfill rental
          application and record-keeping requirements, subject to applicable law.
        </li>

        <li>
          <strong>FCRA Rights</strong>. You understand that you have the right under the FCRA to
          request a copy of any consumer report obtained about you and to dispute any inaccurate
          or incomplete information. If any adverse action is taken against you based in whole or
          in part on information from a Consumer Report, you will receive an Adverse Action Notice
          explaining the action taken and your rights under the FCRA.
        </li>

        <li>
          <strong>Consent to Receive Electronic Notices</strong>. You expressly consent to receive
          notices electronically by email.
        </li>
      </ol>
    </div>
  );
};
