'use client';

import PopularListingsSection from '@/components/home-components/popular-listings-section';
import { ListingAndImages } from '@/types';

// Sample listings data matching the Figma design
const SAMPLE_LISTINGS: ListingAndImages[] = [
  {
    id: 'listing-1',
    title: 'Your Home Away from Home',
    shortestLeasePrice: 6800,
    roomCount: 3,
    bathroomCount: 2,
    category: 'Home',
    state: 'TX',
    listingImages: [{ id: 'img-1', url: '/stock_interior.webp', listingId: 'listing-1', category: 'other', order: 0 }],
    monthlyPricing: [{ id: 'mp-1', listingId: 'listing-1', monthsMin: 1, monthsMax: 1, price: 6800 }],
  } as ListingAndImages,
  {
    id: 'listing-2',
    title: 'Vineyard Paradise',
    shortestLeasePrice: 54800,
    roomCount: 5,
    bathroomCount: 4,
    category: 'House',
    state: 'CA',
    listingImages: [{ id: 'img-2', url: '/stock_interior.webp', listingId: 'listing-2', category: 'other', order: 0 }],
    monthlyPricing: [{ id: 'mp-2', listingId: 'listing-2', monthsMin: 1, monthsMax: 1, price: 54800 }],
  } as ListingAndImages,
  {
    id: 'listing-3',
    title: 'Bay Area Jewel',
    shortestLeasePrice: 10800,
    roomCount: 4,
    bathroomCount: 3,
    category: 'Condo',
    state: 'CA',
    listingImages: [{ id: 'img-3', url: '/stock_interior.webp', listingId: 'listing-3', category: 'other', order: 0 }],
    monthlyPricing: [{ id: 'mp-3', listingId: 'listing-3', monthsMin: 1, monthsMax: 1, price: 10800 }],
  } as ListingAndImages,
  {
    id: 'listing-4',
    title: 'Huge Home in Richmond CA',
    shortestLeasePrice: 3800,
    roomCount: 6,
    bathroomCount: 4,
    category: 'House',
    state: 'CA',
    listingImages: [{ id: 'img-4', url: '/stock_interior.webp', listingId: 'listing-4', category: 'other', order: 0 }],
    monthlyPricing: [{ id: 'mp-4', listingId: 'listing-4', monthsMin: 1, monthsMax: 1, price: 3800 }],
  } as ListingAndImages,
  {
    id: 'listing-5',
    title: 'Your Home Away from Home',
    shortestLeasePrice: 2800,
    roomCount: 2,
    bathroomCount: 1,
    category: 'Apartment',
    state: 'CA',
    listingImages: [{ id: 'img-5', url: '/stock_interior.webp', listingId: 'listing-5', category: 'other', order: 0 }],
    monthlyPricing: [{ id: 'mp-5', listingId: 'listing-5', monthsMin: 1, monthsMax: 1, price: 2800 }],
  } as ListingAndImages,
  {
    id: 'listing-6',
    title: 'House Boat on the Bay',
    shortestLeasePrice: 2700,
    roomCount: 2,
    bathroomCount: 1,
    category: 'Boat',
    state: 'CA',
    listingImages: [{ id: 'img-6', url: '/stock_interior.webp', listingId: 'listing-6', category: 'other', order: 0 }],
    monthlyPricing: [{ id: 'mp-6', listingId: 'listing-6', monthsMin: 1, monthsMax: 1, price: 2700 }],
  } as ListingAndImages,
  {
    id: 'listing-7',
    title: 'SLC Home',
    shortestLeasePrice: 6800,
    roomCount: 4,
    bathroomCount: 3,
    category: 'Home',
    state: 'UT',
    listingImages: [{ id: 'img-7', url: '/stock_interior.webp', listingId: 'listing-7', category: 'other', order: 0 }],
    monthlyPricing: [{ id: 'mp-7', listingId: 'listing-7', monthsMin: 1, monthsMax: 1, price: 6800 }],
  } as ListingAndImages,
  {
    id: 'listing-8',
    title: 'Cozy Home in Farmington',
    shortestLeasePrice: 5800,
    roomCount: 3,
    bathroomCount: 2,
    category: 'Home',
    state: 'UT',
    listingImages: [{ id: 'img-8', url: '/stock_interior.webp', listingId: 'listing-8', category: 'other', order: 0 }],
    monthlyPricing: [{ id: 'mp-8', listingId: 'listing-8', monthsMin: 1, monthsMax: 1, price: 5800 }],
  } as ListingAndImages,
  {
    id: 'listing-9',
    title: 'Ogden Jewel',
    shortestLeasePrice: 10800,
    roomCount: 5,
    bathroomCount: 3,
    category: 'House',
    state: 'UT',
    listingImages: [{ id: 'img-9', url: '/stock_interior.webp', listingId: 'listing-9', category: 'other', order: 0 }],
    monthlyPricing: [{ id: 'mp-9', listingId: 'listing-9', monthsMin: 1, monthsMax: 1, price: 10800 }],
  } as ListingAndImages,
  {
    id: 'listing-10',
    title: 'Ski In and Out in Park City',
    shortestLeasePrice: 3800,
    roomCount: 4,
    bathroomCount: 3,
    category: 'Condo',
    state: 'UT',
    listingImages: [{ id: 'img-10', url: '/stock_interior.webp', listingId: 'listing-10', category: 'other', order: 0 }],
    monthlyPricing: [{ id: 'mp-10', listingId: 'listing-10', monthsMin: 1, monthsMax: 1, price: 3800 }],
  } as ListingAndImages,
  {
    id: 'listing-11',
    title: 'Your Home Away from Home',
    shortestLeasePrice: 2800,
    roomCount: 2,
    bathroomCount: 2,
    category: 'Apartment',
    state: 'UT',
    listingImages: [{ id: 'img-11', url: '/stock_interior.webp', listingId: 'listing-11', category: 'other', order: 0 }],
    monthlyPricing: [{ id: 'mp-11', listingId: 'listing-11', monthsMin: 1, monthsMax: 1, price: 2800 }],
  } as ListingAndImages,
  {
    id: 'listing-12',
    title: 'House Boat on the Bay',
    shortestLeasePrice: 2700,
    roomCount: 1,
    bathroomCount: 1,
    category: 'Boat',
    state: 'UT',
    listingImages: [{ id: 'img-12', url: '/stock_interior.webp', listingId: 'listing-12', category: 'other', order: 0 }],
    monthlyPricing: [{ id: 'mp-12', listingId: 'listing-12', monthsMin: 1, monthsMax: 1, price: 2700 }],
  } as ListingAndImages,
  {
    id: 'listing-13',
    title: 'Your Home Away from Home',
    shortestLeasePrice: 800,
    roomCount: 3,
    bathroomCount: 2,
    category: 'Home',
    state: 'TN',
    listingImages: [{ id: 'img-13', url: '/stock_interior.webp', listingId: 'listing-13', category: 'other', order: 0 }],
    monthlyPricing: [{ id: 'mp-13', listingId: 'listing-13', monthsMin: 1, monthsMax: 1, price: 800 }],
  } as ListingAndImages,
  {
    id: 'listing-14',
    title: 'Vineyard Paradise',
    shortestLeasePrice: 54800,
    roomCount: 6,
    bathroomCount: 5,
    category: 'Estate',
    state: 'TN',
    listingImages: [{ id: 'img-14', url: '/stock_interior.webp', listingId: 'listing-14', category: 'other', order: 0 }],
    monthlyPricing: [{ id: 'mp-14', listingId: 'listing-14', monthsMin: 1, monthsMax: 1, price: 54800 }],
  } as ListingAndImages,
  {
    id: 'listing-15',
    title: 'Bay Area Jewel',
    shortestLeasePrice: 10800,
    roomCount: 4,
    bathroomCount: 3,
    category: 'Condo',
    state: 'TN',
    listingImages: [{ id: 'img-15', url: '/stock_interior.webp', listingId: 'listing-15', category: 'other', order: 0 }],
    monthlyPricing: [{ id: 'mp-15', listingId: 'listing-15', monthsMin: 1, monthsMax: 1, price: 10800 }],
  } as ListingAndImages,
  {
    id: 'listing-16',
    title: 'Huge Home in Richmond CA',
    shortestLeasePrice: 3800,
    roomCount: 5,
    bathroomCount: 4,
    category: 'House',
    state: 'TN',
    listingImages: [{ id: 'img-16', url: '/stock_interior.webp', listingId: 'listing-16', category: 'other', order: 0 }],
    monthlyPricing: [{ id: 'mp-16', listingId: 'listing-16', monthsMin: 1, monthsMax: 1, price: 3800 }],
  } as ListingAndImages,
  {
    id: 'listing-17',
    title: 'Your Home Away from Home',
    shortestLeasePrice: 2800,
    roomCount: 2,
    bathroomCount: 2,
    category: 'Apartment',
    state: 'TN',
    listingImages: [{ id: 'img-17', url: '/stock_interior.webp', listingId: 'listing-17', category: 'other', order: 0 }],
    monthlyPricing: [{ id: 'mp-17', listingId: 'listing-17', monthsMin: 1, monthsMax: 1, price: 2800 }],
  } as ListingAndImages,
  {
    id: 'listing-18',
    title: 'House Boat on the Bay',
    shortestLeasePrice: 2700,
    roomCount: 2,
    bathroomCount: 1,
    category: 'Boat',
    state: 'TN',
    listingImages: [{ id: 'img-18', url: '/stock_interior.webp', listingId: 'listing-18', category: 'other', order: 0 }],
    monthlyPricing: [{ id: 'mp-18', listingId: 'listing-18', monthsMin: 1, monthsMax: 1, price: 2700 }],
  } as ListingAndImages,
  {
    id: 'listing-19',
    title: 'Your Home Away from Home',
    shortestLeasePrice: 6800,
    roomCount: 4,
    bathroomCount: 3,
    category: 'Home',
    state: 'NV',
    listingImages: [{ id: 'img-19', url: '/stock_interior.webp', listingId: 'listing-19', category: 'other', order: 0 }],
    monthlyPricing: [{ id: 'mp-19', listingId: 'listing-19', monthsMin: 1, monthsMax: 1, price: 6800 }],
  } as ListingAndImages,
  {
    id: 'listing-20',
    title: 'Pool Playhouse in Vegas',
    shortestLeasePrice: 54800,
    roomCount: 6,
    bathroomCount: 5,
    category: 'Mansion',
    state: 'NV',
    listingImages: [{ id: 'img-20', url: '/stock_interior.webp', listingId: 'listing-20', category: 'other', order: 0 }],
    monthlyPricing: [{ id: 'mp-20', listingId: 'listing-20', monthsMin: 1, monthsMax: 1, price: 54800 }],
  } as ListingAndImages,
  {
    id: 'listing-21',
    title: 'Condo in Vegas',
    shortestLeasePrice: 10800,
    roomCount: 3,
    bathroomCount: 2,
    category: 'Condo',
    state: 'NV',
    listingImages: [{ id: 'img-21', url: '/stock_interior.webp', listingId: 'listing-21', category: 'other', order: 0 }],
    monthlyPricing: [{ id: 'mp-21', listingId: 'listing-21', monthsMin: 1, monthsMax: 1, price: 10800 }],
  } as ListingAndImages,
  {
    id: 'listing-22',
    title: 'Massive Condo in Vegas',
    shortestLeasePrice: 3800,
    roomCount: 4,
    bathroomCount: 3,
    category: 'Condo',
    state: 'NV',
    listingImages: [{ id: 'img-22', url: '/stock_interior.webp', listingId: 'listing-22', category: 'other', order: 0 }],
    monthlyPricing: [{ id: 'mp-22', listingId: 'listing-22', monthsMin: 1, monthsMax: 1, price: 3800 }],
  } as ListingAndImages,
  {
    id: 'listing-23',
    title: 'Penthouse Suite in Caesars',
    shortestLeasePrice: 2800,
    roomCount: 2,
    bathroomCount: 2,
    category: 'Suite',
    state: 'NV',
    listingImages: [{ id: 'img-23', url: '/stock_interior.webp', listingId: 'listing-23', category: 'other', order: 0 }],
    monthlyPricing: [{ id: 'mp-23', listingId: 'listing-23', monthsMin: 1, monthsMax: 1, price: 2800 }],
  } as ListingAndImages,
  {
    id: 'listing-24',
    title: 'Spacious Home in the Desert',
    shortestLeasePrice: 2700,
    roomCount: 5,
    bathroomCount: 3,
    category: 'House',
    state: 'NV',
    listingImages: [{ id: 'img-24', url: '/stock_interior.webp', listingId: 'listing-24', category: 'other', order: 0 }],
    monthlyPricing: [{ id: 'mp-24', listingId: 'listing-24', monthsMin: 1, monthsMax: 1, price: 2700 }],
  } as ListingAndImages,
];

export default function FigmaPage() {
  return (
    <div className="min-h-screen bg-white">
      <header className="border-b py-4 px-6">
        <h1 className="text-2xl font-semibold text-gray-800">Matchbook 2.0 - Figma Design Preview</h1>
        <p className="text-sm text-gray-500 mt-1">Homepage Listings Section from Figma</p>
      </header>
      <main>
        <PopularListingsSection listings={SAMPLE_LISTINGS} />
      </main>
    </div>
  );
}
