import { SignIn } from "@clerk/nextjs";

export default function Page() {
  return (
    <SignIn 
      appearance={{
        elements: {
          formButtonPrimary: "",
          formButtonReset: "",
          card: "p-0 bg-background",
          cardBox: "border-none shadow-none",
          header: "",
          headerTitle: "text-[28px] font-medium ",
          footer: "bg-background",
          form: "",
          formContainer: "",
          identityPreviewText: "",
          identityPreviewEditButton: "",
          otpCodeFieldInputs: "",
          otpCodeField: "",
          formFieldAction: "",
          formField: "",
          formFieldLabel: "",
          formFieldLabelRow: "",
          formFieldInput: "",
          formFieldInputGroup: "",
          formFieldError: "",
          formHeaderTitle: "",
          formHeaderSubtitle: "",
          footerAction: "bg-background w-full flex justify-center",
          footerActionText: "bg-background",
          footerActionLink: "bg-background",
          formResendCodeLink: "",
          formFieldWarning: "",
          formFieldHintText: "",
          formFieldSuccessText: "",
          socialButtonsContainer: "",
          socialButtonsBlockButton: "w-[95%] first:flex first:justify-between " ,
          socialButtonsBlockButton__apple: "",
          socialButtonsBlockText: "inline-block" ,
          socialButtons: "flex flex-col items-center",
          socialButtonsIconButton: "",
          socialButtonsProviderIcon: "",
          providerIcon: "",
          logoBox: "",
          logoImage: "",
          dividerContainer: "",
          dividerText: "",
          rootBox: "",
          main: "",
          page: "",
          pageScrollBox: "",
          badge: "",
          avatarBox: "",
          avatarImage: "",
          profileSwitcherTrigger: "",
          userPreview: "",
          userPreviewAvatarBox: "",
          userPreviewAvatarImage: "",
          userPreviewTextContainer: "",
          userButtonBox: "",
          userButtonTrigger: "",
          userButtonPopoverCard: "",
          userButtonPopoverMain: "",
          userButtonPopoverActions: "",
          userButtonPopoverActionButton: "",
          userButtonPopoverFooter: "",
          modalBackdrop: "",
          modalContent: "",
          modalCloseButton: "",
          navbarMobileMenuButton: "",
          navbarButton: "",
          accordionTriggerButton: "",
          accordionContent: "",
          breadcrumbs: "",
          breadcrumbsItem: "",
          breadcrumbsItemDivider: "",
          breadcrumbsItemButton: "",
          alert: "",
          alertIcon: "",
          alertText: "",
          alertTitle: "",
          formSuccessScreen: "",
          spinner: "",
          virtualSignupPage: "",
          phoneInputBox: "",
          phoneInputBoxInput: "",
          phoneInputBoxMenu: "",
          phoneInputBoxMenuList: "",
          phoneInputBoxMenuItem: "",
          phoneInputBoxTrigger: "",
          phoneInputBoxTriggerIcon: "",
          phoneInputBoxDialCode: "",
          phoneInputBoxFlag: "",
          twoStepSecondFactorText: "",
          twoStepAlternativesText: "",
          twoStepTOTPTitle: "",
          twoStepTOTPHero: "",
          twoStepTOTPQRCodeContainer: "",
          twoStepTOTPQRCode: "",
          twoStepTOTPSecretKey: "",
          twoStepTOTPSecretKeyContainer: "",
          twoStepTOTPSecretKeyText: "",
        }
      }}
    />
  );
}
